baseURL = 'http://example.org/'
languageCode = 'en-gb'
title = 'Website Name'
theme = 'themename'
buildFuture = true
enableGitInfo = true

[taxonomies]
  category = 'categories'

[permalinks]
  events = '/events/:year/:month/:title/'
